/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "IBalancerV2Vault",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IBalancerV2Vault__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "ILongShortPairContract",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ILongShortPairContract__factory>;
    getContractFactory(
      name: "IWrappedNativeToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IWrappedNativeToken__factory>;
    getContractFactory(
      name: "SPunkWrapper",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SPunkWrapper__factory>;

    getContractAt(
      name: "IBalancerV2Vault",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IBalancerV2Vault>;
    getContractAt(
      name: "IERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "ILongShortPairContract",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ILongShortPairContract>;
    getContractAt(
      name: "IWrappedNativeToken",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IWrappedNativeToken>;
    getContractAt(
      name: "SPunkWrapper",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.SPunkWrapper>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
