/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  PayableOverrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface SPunkWrapperInterface extends ethers.utils.Interface {
  functions: {
    "longPunkToken()": FunctionFragment;
    "mintAndSell(uint8,address,bytes32,uint256)": FunctionFragment;
    "shortPunkToken()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "longPunkToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "mintAndSell",
    values: [BigNumberish, string, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "shortPunkToken",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "longPunkToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintAndSell",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "shortPunkToken",
    data: BytesLike
  ): Result;

  events: {};
}

export class SPunkWrapper extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: SPunkWrapperInterface;

  functions: {
    longPunkToken(overrides?: CallOverrides): Promise<[string]>;

    mintAndSell(
      direction: BigNumberish,
      vault: string,
      poolId: BytesLike,
      amount: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    shortPunkToken(overrides?: CallOverrides): Promise<[string]>;
  };

  longPunkToken(overrides?: CallOverrides): Promise<string>;

  mintAndSell(
    direction: BigNumberish,
    vault: string,
    poolId: BytesLike,
    amount: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  shortPunkToken(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    longPunkToken(overrides?: CallOverrides): Promise<string>;

    mintAndSell(
      direction: BigNumberish,
      vault: string,
      poolId: BytesLike,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    shortPunkToken(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    longPunkToken(overrides?: CallOverrides): Promise<BigNumber>;

    mintAndSell(
      direction: BigNumberish,
      vault: string,
      poolId: BytesLike,
      amount: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    shortPunkToken(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    longPunkToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    mintAndSell(
      direction: BigNumberish,
      vault: string,
      poolId: BytesLike,
      amount: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    shortPunkToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
